### ISSUE TITLE
date issue

### ISSUE THREAD

**Issue by blimeybloke** [alexandrianlibrarian/eweipc#1]
Thanks for posting the code to this on Reddit.
I am trying to run it and had to do:
sudo apt-get install dnsutils

But I am still getting:
sudo bash eweipc.bash
eweipc.bash: 17: eweipc.bash: ./getip.bash: Permission denied
date: unrecognized option '--rfc-email'
Try 'date --help' for more information.
eweipc.bash: 39: eweipc.bash: [[: not found

Any suggestion?  I am running that to test it out tbh.
I named my netrc.conf to that, put the absolute path of /download/eweipc/netrc.conf

Cheers

**Comment by blimeybloke** [comment]
After redoing the install, and chmod 777 everything, I now get:
> bash eweipc.bash
date: unrecognized option '--rfc-email'
Try 'date --help' for more information.

so getting further but still that date issue.

**Comment by blimeybloke** [comment]
The script does work though even with that error.

**Comment by alexandrianlibrarian** [comment]
Thanks for reminding me that  dnsutils is required! I totally forgot to include that in the documentation and reddit post. I'm working on looking into the date issue.

**Comment by alexandrianlibrarian** [comment]
For "eweipc.bash: 17: eweipc.bash: ./getip.bash: Permission denied" you need to make sure that you give getip.bash permissions to execute as well.

**Comment by alexandrianlibrarian** [comment]
> After redoing the install, and chmod 777 everything, I now get:
> 
> > bash eweipc.bash
> > date: unrecognized option '--rfc-email'
> > Try 'date --help' for more information.
> 
> so getting further but still that date issue.

It has to do with the version of the date GNU coreutil. Seems like Raspbian's default is GNU coreutils 8.26. Could you let me know if this is the same for you? I have GNU coreutils 8.28 on my Ubuntu PC and that version of date has the "--rfc-email." option. Getting your GNU coreutils updated to that version should solve the problem. Once again, thanks for bringing this to my attention! I'll make sure to include it in the notes.

**Comment by alexandrianlibrarian** [comment]
Please do let me know if that solves all your problems so we can successfully close this issue. :)

**Comment by blimeybloke** [comment]
Sorry to ask, how do I do find that version out?

**Comment by alexandrianlibrarian** [comment]
> Sorry to ask, how do I do find that version out?

Please, no need to be sorry! You can do that by:
$ man date
Then hit Shift+G to go to the bottom of the page and it should show you the version you have.

**Comment by blimeybloke** [comment]
thanks GNU coreutils 8.26

**Comment by alexandrianlibrarian** [comment]
That version doesn't have the "--rfc-email" option for the date program.

**Comment by blimeybloke** [comment]
No problem.  The script still runs like it should.  I receive emails and it is a huge help for me to see when my IP changes or my primary ISP hiccups and my secondary kicks in.  Thanks for sharing this code.

If my pi didn't have other things, I would be a bit more adventurous and do a apt-get dist-upgrade but everything functions fine.

**Comment by alexandrianlibrarian** [comment]
I'm glad it's still running as it should! Thank you for the quick communication. Since you don't want to upgrade, I will see if I can quickly fix the date field for the email to be manually generated. I'll write here again with updates when they're ready.

**Comment by blimeybloke** [comment]
oh wow, thanks for that. 0 rush obviously lol

**Comment by alexandrianlibrarian** [comment]
I've updated the code. Can you try with setting up with the new code and tell me how it goes, please?

**Comment by alexandrianlibrarian** [comment]
Also, chmod 755 should be sufficient for the *.bash files.

**Comment by blimeybloke** [comment]
That solved the issue.  Cheers!

**Comment by alexandrianlibrarian** [comment]
You're welcome! Again, thanks for being so quick to bring up and help me deal with this issue.
Best wishes! :)
