### ISSUE TITLE
Fail and retry

### ISSUE THREAD

**Issue by blimeybloke** [alexandrianlibrarian/eweipc#2]
Not sure if this is an issue as much as a request for a minor update.  It seems that every few checks off and on, I get an email that my IP changed to .  and then the next check it is still my old IP.

I am thinking that maybe a simple 2 or 3 retries if it gets a null IP, or it just skips the email for a null IP?

Cheers

**Comment by alexandrianlibrarian** [comment]
Thanks for bringing up this issue. I'm going to have to think about why it's been behaving this way.

**Comment by alexandrianlibrarian** [comment]
I've updated the script getip.bash to ensure it doesn't give empty output. Please do let me know if this fixes the issue. :)

**Comment by blimeybloke** [comment]
Looks good so far.  Will report if I see further issues.  Sorry if I am being a pain :)

**Comment by alexandrianlibrarian** [comment]
I'm glad you're bringing up these issues! I adapted this program a lot to make it user-friendly to use and am very glad to see it actually being useful to someone. So please, don't worry about it. :)

**Comment by alexandrianlibrarian** [comment]
@blimeybloke , is everything functioning alright now?

**Comment by blimeybloke** [comment]
yes, so far no further issues.  thanks again for your work

**Comment by alexandrianlibrarian** [comment]
Excellent! And you're welcome!
